### ISSUE TITLE
TD-V7 Roadmap

### ISSUE THREAD

**Issue by fuzzbuck** [fuzzbuck/Mindustry#51]
### Features marked with [x] are completed.
_Contributors will get the Content Creator rank & will be mentioned in this Roadmap_

**Various more features could be added here with no notice
If you want to contribute to a feature, please comment below !
you will be assigned to that feature
( we don't want multiple people working on the same thing )**

- [x]  migrate unit drops
- [x] turret rebalancing
- [x] repair points give damage boost instead of heal
- [x] prevent core interactions w/ logic
- [x] nerf mender <-> core interactions, make mender electrify enemies
- [x] make force projectors (& force projector ability) weaken enemy units (make them take 1.5x more damage)
- [x] make players unable to build on path
- [x] make shock mines buildable on path

- [x] unit drops hud (toggle-able)
- [x] unit drops effects (resources -> core, maybe sound fx?)
- [x] migrate wave & unit health multiplier

- [x] basic pathfinding setup
- [x] pathfinding - ground units follow darkPanel4, cant go outside darkPanel5
- [x] pathfinding - air units go straight to the core
- [x] pathfinding - water units remain unchanged

- [x] enemy units do not shoot, unless close to the core, in which case they explode and deal damage to the closest core
- [x] (NiChrosia) prevent enemy spiders from dealing damage with their feet
- [x] prevent enemy flying units from dealing damage upon collapsing
- [x] enemy units can not collide with friendly units (prevent blocking)
- [x] buff oct (better force field)
- [x] #52 

- [x] sending units to spawn as enemies (achieve this by using payload void, when unit is inserted into it, spawn the same unit on waveTeam on the nearest unit drop point
- [x] space floor kills units (team divider)

**Comment by woop-3533** [comment]
h

**Comment by buthed010203** [comment]
[Milestone](https://github.com/fuzzbuck/Mindustry/milestones) when

or even better, a [project](https://github.com/fuzzbuck/Mindustry/projects)

**Comment by buthed010203** [comment]
> enemy units do not shoot, unless close to the core, in which case they explode and deal damage to the closest core

this one is super easy, apply the disarmed status effect for Integer.MAX_VALUE when they spawn

edit: how much damage should they deal and what range should they explode from?

**Comment by TranquillyUnpleasant** [comment]
> edit: how much damage should they deal and what range should they explode from?

Proportional to their health + shield strength (force field units may need tweaking)
Range should just be when their hitbox collides with the core, since theyre supposed to explode on direct impact.

**Comment by w4536p** [comment]
what should the item drop sound effect sound like

**Comment by AnoyingShulkerMC** [comment]
Would the units also avoid shit that isn't DarkPanel4

**Comment by fuzzbuck** [comment]
I will work on pathfinding

**Comment by AnoyingShulkerMC** [comment]
I'd work on AI
>  enemy units do not shoot, unless close to the core, in which case they explode and deal damage to the closest core

**Comment by AnoyingShulkerMC** [comment]
> > enemy units do not shoot, unless close to the core, in which case they explode and deal damage to the closest core
> 
> this one is super easy, apply the disarmed status effect for Integer.MAX_VALUE when they spawn
> 
> edit: how much damage should they deal and what range should they explode from?

@buthed010203 ok, but they would explode right?

**Comment by buthed010203** [comment]
> > > enemy units do not shoot, unless close to the core, in which case they explode and deal damage to the closest core
> > 
> > 
> > this one is super easy, apply the disarmed status effect for Integer.MAX_VALUE when they spawn
> > edit: how much damage should they deal and what range should they explode from?
> 
> @buthed010203 ok, but they would explode right?

Ofc they would, exploding is relatively simple as well. Simply add a bit of code to CoreBuild's update method that uses Units.closestEnemy, checks if its within a block or whatever then spawn an explosion particle and deal damage accordingly (the explosion wouldnt actually be the unit attacking).

**Comment by AnoyingShulkerMC** [comment]
> enemy units can not collide with friendly units
>
What would the friendly units do @fuzzbuck

**Comment by AnoyingShulkerMC** [comment]
> > > > enemy units do not shoot, unless close to the core, in which case they explode and deal damage to the closest core
> > > 
> > > 
> > > this one is super easy, apply the disarmed status effect for Integer.MAX_VALUE when they spawn
> > > edit: how much damage should they deal and what range should they explode from?
> > 
> > 
> > @buthed010203 ok, but they would explode right?
> 
> Ofc they would, exploding is relatively simple as well. Simply add a bit of code to CoreBuild's update method that uses Units.closestEnemy, checks if its within a block or whatever then spawn an explosion particle and deal damage accordingly (the explosion wouldnt actually be the unit attacking).
~~i use a different approach~~
`package mindustry.ai.types;

import mindustry.entities.units.AIController;
import mindustry.gen.Teamc;
// i'm bad at this
public class TDFlyingSuicideAI extends AIController {
    @Override
    public void updateMovement() {
        /*The story ends*/
        if(target == null) return;
        moveTo(target, unit.type.range * 0.8f);
        unit.controlWeapons(unit.within(target, 3f)); //idk why this not working
    }

    @Override
    public Teamc findTarget(float x, float y, float range, boolean air, boolean ground) {
        return unit.closestEnemyCore();
    }
}`

**Comment by AnoyingShulkerMC** [comment]
> > > > enemy units do not shoot, unless close to the core, in which case they explode and deal damage to the closest core
> > > 
> > > 
> > > this one is super easy, apply the disarmed status effect for Integer.MAX_VALUE when they spawn
> > > edit: how much damage should they deal and what range should they explode from?
> > 
> > 
> > @buthed010203 ok, but they would explode right?
> 
> Ofc they would, exploding is relatively simple as well. Simply add a bit of code to CoreBuild's update method that uses Units.closestEnemy, checks if its within a block or whatever then spawn an explosion particle and deal damage accordingly (the explosion wouldnt actually be the unit attacking).

lol, i use a different approach, which is swapping out w/ crawler weapons
and swapping them w/ new ai

edit: Would sharded crawler, sharded flare etc. be allowed in td?

**Comment by fuzzbuck** [comment]
> 
> 
> > > > > enemy units do not shoot, unless close to the core, in which case they explode and deal damage to the closest core
> > > > 
> > > > 
> > > > this one is super easy, apply the disarmed status effect for Integer.MAX_VALUE when they spawn
> > > > edit: how much damage should they deal and what range should they explode from?
> > > 
> > > 
> > > @buthed010203 ok, but they would explode right?
> > 
> > 
> > Ofc they would, exploding is relatively simple as well. Simply add a bit of code to CoreBuild's update method that uses Units.closestEnemy, checks if its within a block or whatever then spawn an explosion particle and deal damage accordingly (the explosion wouldnt actually be the unit attacking).
> 
> lol, i use a different approach, which is swapping out w/ crawler weapons
> and swapping them w/ new ai
> 
> edit: Would sharded crawler, sharded flare etc. be allowed in td?

this approach would be friendly units unusable

**Comment by buthed010203** [comment]
> this approach would be friendly units unusable

Wouldn't this also cause desync resulting in the enemies still shooting client side?

**Comment by fuzzbuck** [comment]
most features are finished. if there are any new cool ideas they will be posted here so keep an eye out
